name: Merge DEV into PROD

on:
  push:
    branches:
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
       
       with:
       ref main:

    - name: Test changes
      run: |
        echo "Running tests"
        # Run tests here

    - name: Merge  to PROD
   
      run: |
        git checkout PROD
        git merge DEV
        git push origin RROD
