

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Fetch origin
      run: |
        git remote set-url origin https://github.com 9aveed/project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.git
        git fetch origin

    - name: Checkout prod branch
      run: |
        git checkout prod
        git pull origin prod

    - name: Merge dev into prod
      run: |
        git merge dev
        git push origin prod
